# Generated by Django 2.1.1 on 2020-11-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_auto_20201125_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
